### ISSUE TITLE
An SSL error has occurred.

### ISSUE THREAD

**Issue by zondaxxx** [MNasybullin/Anilibria-ios-app#41]
Вылезает ошибка при запуске приложения, что делать?

**Comment by MNasybullin** [comment]
Привет, нужно больше подробностей. Как устанавливал приложение (Xcode, ipa)? Устройство, версия os, и скрин c ошибкой

**Comment by zondaxxx** [comment]
Ставил ipa, подписывал сертификатом разработчика через Gbox / Feather. Версия 18.0, Iphone 12 Pro Max
![image](https://github.com/user-attachments/assets/090662fc-3e3e-4c7a-99aa-ef6ac51047b2)

**Comment by zondaxxx** [comment]
Есть подозрение что API используется от сайта заблокированного в РФ. С ВПН работает, но столкнулся с другой проблемой - не работает вход
Если логин пароль неправильные - выдает ошибку пользователя или пароля. Но если логин и пароль верные пишет data could not be read because it is missing. ![image](https://github.com/user-attachments/assets/2deb8c83-9ac5-4586-8e2e-fc046b3aef97)

**Comment by MNasybullin** [comment]
Странно, сейчас проверил у себя, без впн работает и в аккаунт входит. Понизил уровень безопасности в приложении. Попробуй эту версию 
[AniLibria_1.0.2.ipa.zip](https://github.com/user-attachments/files/17210984/AniLibria_1.0.2.ipa.zip)

**Comment by zondaxxx** [comment]
ошибка немного изменилась)
Теперь выдает стандартную ошибку  при небезопасном сайте![image](https://github.com/user-attachments/assets/963376e8-002f-46cf-a061-0cb175219785)

**Comment by zondaxxx** [comment]
Ради интереса установил программу через AltStore. Ситуация не изменилась

**Comment by MNasybullin** [comment]
На счет ошибки SSL и сертификата, скорее всего проблема у вашего провайдера, раз с впн все работает. Попробуйте другие wifi сети, мобильные данные. А в личный кабинет так и не удалось попасть?

**Comment by zondaxxx** [comment]
ну похоже что да, мегафон не пропускает апи анилибрии.
С личным тоже самое что было, не получилось войти

**Comment by zondaxxx** [comment]
Хотя в нативном приложении анилибрии на ios (на гитхабе есть) все работает
может стоит попробовать перенести api оттуда?

**Comment by MNasybullin** [comment]
API у нас одинаковое, различия только в том, что они используют зеркала. Переделывать на зеркала смысла не вижу. Потому что неизвестно как долго будут работать старые сервера и старые api. Тк они выпустили новый сайт с новым api.

**Comment by zondaxxx** [comment]
сегодня протестил у другого провайдера. 
Само приложение работает прекрасно, но аккаунт так и не заработал

**Comment by MNasybullin** [comment]
Попробуй зайти в тестовый аккаунт. логин - anilibria_test@mail.ru пароль - TestPasswordTest  
Если на аккаунте у тебя есть двухфакторная аутентификации (вход с одноразовым кодом), то проблема в ней.

**Comment by zondaxxx** [comment]
Хм, интересно. В твой аккаунт у меня войти получилось, потом я попытался зарегистрировать два новых аккаунта, но оно не пропустило с той же ошибкой :/

**Comment by zondaxxx** [comment]
при этом двухфакторки у меня не стоит
на каком сайте/зеркале ты регистрировал аккаунт для теста?

**Comment by MNasybullin** [comment]
Исправил, можешь загрузить новую версию https://github.com/MNasybullin/Anilibria-ios-app/releases/tag/1.0.2
Они изменили модель данных для новый акаунтов. Из-за этого и не получалось войти.

**Comment by zondaxxx** [comment]
![image](https://github.com/user-attachments/assets/51bb0dc9-1da3-43c6-8a11-bb3a5ef076f8)
Ура, спасибо! Буду с кайфом пользоваться
